Repository sfeye/Event-App, pull requests merged in 2021-06, with the labels that each got.

#5 😅 Ok we should be setup now 🤗
  src/App.js
  src/assets/logo.png
  src/components/CreateEvent.js
  src/components/Event.js
  src/components/Friends.js
  src/components/Search.js
  src/components/Settings.js
  src/package-lock.json
  src/package.json
  src/pages/CreateAccount.js
  src/pages/Dashboard.js
  src/pages/Loading.js
  src/pages/Login.js
  src/yarn.lock
Labels: enhancement

#6 added login and signup forms
  src/package.json
  src/pages/CreateAccount.js
  src/pages/Login.js
  src/yarn.lock
Labels: enhancement

#7 🥉 Can successfully create an event on the db 🥱 but thats it...
  src/App.js
  src/components/CreateEvent.js
  src/components/InviteFriends.js
  src/package.json
  src/yarn.lock
Labels: good first issue

#8 ✨Able to create new events and then have them displayed on the home page✨
  src/App.js
  src/components/CreateEvent.js
  src/components/Event.js
  src/components/EventCard.js
  src/package.json
  src/pages/Dashboard.js
  src/pages/Home.js
  src/yarn.lock
Labels: enhancement

#11 🤡 Can now see data cards for friends 👽
  src/App.js
  src/components/FriendPageComponents/FriendCard.js
  src/components/FriendPageComponents/FriendCards.js
  src/components/FriendPageComponents/Friends.js
  src/components/Friends.js
Labels: Component, Feature, Important

#12 🐛 Remove serializable warning 🐞
  src/App.js
  src/components/CreateEvent.js
  src/components/FriendPageComponents/FriendCard.js
  src/components/FriendPageComponents/Friends.js
  src/pages/Home.js
Labels: bug

#16 👩‍🍳 complete profile page 👨‍🍳
  src/App.js
  src/components/CreateEventComponents/CreateEvent.js
  src/components/CreateEventComponents/InviteFriendCard.js
  src/components/EventCard.js
  src/components/FriendPageComponents/Friends.js
  src/components/Settings.js
  src/components/SettingsPageComponents/EditFriends.js
  src/components/SettingsPageComponents/Settings.js
  src/pages/Home.js
Labels: Component, Feature, Service

#17 add new friends functionality
  src/App.js
  src/components/AddFriendResults.js
  src/components/AddNewFriends.js
  src/components/FriendPageComponents/Friends.js
  src/components/Search.js
  src/package.json
  src/yarn.lock
Labels: Component, Feature, Important, Service

#18 updated search friends to return searched user
  src/components/AddNewFriends.js
  src/pages/CreateAccount.js
Labels: Component, Feature, Important, enhancement

#19 ✅ validations ❌ disabling ♻️ refactor invite friends
  .DS_Store
  node_modules/.yarn-integrity
  src/App.js
  src/components/CreateEventComponents/CreateEvent.js
  src/components/CreateEventComponents/InviteFriends.js
  src/components/EventCard.js
  src/components/ForgotPassword.js
  src/components/SettingsPageComponents/Settings.js
  src/pages/CreateAccount.js
  src/pages/Login.js
Labels: Feature, enhancement

#20 😺 invited friends button to show who is invited to an event 🙀
  src/App.js
  src/components/CreateEventComponents/CreateEvent.js
  src/components/EventCard.js
  src/components/FriendPageComponents/FriendCard.js
  src/components/FriendPageComponents/FriendCards.js
  src/components/FriendPageComponents/FriendProfile.js
  src/components/FriendPageComponents/Friends.js
  src/components/SettingsPageComponents/Settings.js
  src/package.json
  src/pages/Home.js
  src/yarn.lock
Labels: Component, Feature, Important

#22 added accepting friend requests functionality
  src/App.js
  src/components/AddFriendResults.js
  src/components/FriendPageComponents/Friends.js
  src/components/PendingFriendRequests.js
Labels: Component, Feature, Important, Service, enhancement

#23 🌈 Stylings day 1 🎨
  src/App.js
  src/components/CreateEventComponents/CreateEvent.js
  src/components/CreateEventComponents/InviteFriendCard.js
  src/components/FriendPageComponents/AddFriendResults.js
  src/components/FriendPageComponents/AddNewFriends.js
  src/components/FriendPageComponents/FriendCard.js
  src/components/FriendPageComponents/FriendCards.js
  src/components/FriendPageComponents/FriendProfile.js
  src/components/FriendPageComponents/Friends.js
  src/components/FriendPageComponents/PendingFriendRequests.js
  src/components/HomePageComponents/EventCard.js
  src/components/HomePageComponents/EventInvited.js
  src/components/LoginPageComponents/CreateAccount.js
  src/components/LoginPageComponents/ForgotPassword.js
  src/components/SearchPageComponents/Search.js
  src/components/SearchPageComponents/SearchResults.js
  src/components/SettingsPageComponents/EditFriends.js
  src/components/SettingsPageComponents/Settings.js
  src/pages/Home.js
Labels: Feature, bug
